// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1:string,arg2:Array<string>):Promise<string>;

export function GetTags(arg1:string,arg2:number):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
